name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build App
      run: |
        # 显示工作目录
        pwd
        # 创建构建目录
        mkdir -p build
        # 构建应用
        xcodebuild -scheme AutoMessage -configuration Release clean build -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        # 列出构建目录内容
        ls -la build
        # 创建目标目录
        mkdir -p build/AutoMessage
        # 复制应用
        cp -r build/Build/Products/Release/AutoMessage.app build/AutoMessage/
    
    - name: Create ZIP
      run: |
        cd build/AutoMessage
        zip -r ../AutoMessage.app.zip AutoMessage.app
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/AutoMessage.app.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 