name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build App
      run: |
        xcodebuild -scheme AutoMessage -configuration Release clean archive -archivePath build/AutoMessage.xcarchive
        xcodebuild -exportArchive -archivePath build/AutoMessage.xcarchive -exportPath build/AutoMessage -exportOptionsPlist exportOptions.plist
    
    - name: Create ZIP
      run: |
        cd build/AutoMessage
        zip -r ../AutoMessage.app.zip AutoMessage.app
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/AutoMessage.app.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 